### ISSUE TITLE
irco import not working with new release irco 0.9

### ISSUE THREAD

**Issue by asiddiqi14** [GaretJax/irco#12]
I upgraded my irco version to 0.9 and I get an error when I run the irco-import command. I am sending you the error log. I was importing the same datafiles as I have used before with irco, so I don't think it is an issue with the data files.

**Comment by GaretJax** [comment]
Yes, I am now stricter regarding the encoding of the files to import. Normally it should work, but with a format from WoS it now fails (it's not clear if the file is encoded correctly or not).

You have the following choices:
 1) Tab delimited (Win): works if you add `-e utf16` to the command line paramters
 2) Tab delimited (Mac): does not work
 3) Tab delimited (Win, UTF-8): works out of the box
 4) Tab delimited (Mac, UTF-8): works out of the box

You can get a new set of files by using `irco-scrape`. Note, however, that they changed their requests format slightly and it is not working anymore in 0.9.0. I will be releasing 0.9.1 shortly with a fix for this issue. When using `irco-scrape` the correct encoding is chosen for you.
