### ISSUE TITLE
improving author affiliation data

### ISSUE THREAD

**Issue by asiddiqi14** [GaretJax/irco#14]
I found the following issue when analyzing detailed data for Qatar. For publication year 1985 there are a total of 15 records in the raw data file (in savedrecs-8.txt). See rows 486 to 500 when you open this .txt file in excel. Of these 15 records, I get 11 to be imported in the database when I run the irco-import command. I checked the author affiliation information in the RP field, and I find that of the four records that are not included (in rows 489, 491, 497 and 498), two of them have clear reprint author information. Row 491 and Row 497 show reprint author information clearly, however the affilation of other authors in the papers is unclear (as seen in field C1). In these cases (where reprint author info is available) but other authors are unclear, let's include these records also. And in such cases, let's put in a 'NA' or some other data for the missing affiliation of the other authors. This would then allow us to do a better counting of papers by corresponding author countries which is an important part of the analysis.

**Comment by GaretJax** [comment]
In case of ambiguous affiliations, all authors are added to the database with a single affiliation to the first listed institution. If RP information is available, this is used to get more precise affiliation information; if not, the first author and the first institution form the RP information.

These changes are available in irco >= 0.10.1
