### ISSUE TITLE
adding first author affiliation field

### ISSUE THREAD

**Issue by asiddiqi14** [GaretJax/irco#15]
This issue builds on the request in issue 14. 

In many cases, the papers have missing reprint author information. In those cases, it would be useful if we can use first author affiliation instead. Can we add another field in the publications table that stores first author affiliation? This would then allow us to run queries in which we specify the corresponding author country and if that is missing, to then use first author affiliation country to search for publications.

**Comment by GaretJax** [comment]
This already works that way.
