### ISSUE TITLE
country affiliation for UAE data

### ISSUE THREAD

**Issue by asiddiqi14** [GaretJax/irco#16]
I have noted that in my records the country affiliation for publications from UAE is not being recorded. I get messages in the terminal window when running the irco-graph command and irco-import command. In many cases the name is given in the record as U Arab Emirates. I am attaching a screen shot here:

**Comment by GaretJax** [comment]
U Arab Emirates already is detected correctly. I think the issue here is that the institution name terminates with a full stop. As of 0.10.2 I am now ignoring them when matching country names.
